# Generated by Django 5.2.9 on 2026-01-03 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_parcel_drop_lat_parcel_drop_lng_parcel_pickup_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignment', to='client.parcel')),
            ],
            options={
                'verbose_name': 'Driver Assignment',
                'verbose_name_plural': 'Driver Assignments',
                'db_table': 'driver_assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['driver', '-assigned_at'], name='driver_assi_driver__50eb03_idx'), models.Index(fields=['parcel'], name='driver_assi_parcel__d783d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude coordinate', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude coordinate', max_digits=10)),
                ('address', models.CharField(blank=True, help_text='Address or location description', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_locations', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_locations', to='client.parcel')),
            ],
            options={
                'verbose_name': 'Driver Location',
                'verbose_name_plural': 'Driver Locations',
                'db_table': 'driver_locations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['driver', '-timestamp'], name='driver_loca_driver__67c437_idx'), models.Index(fields=['parcel', '-timestamp'], name='driver_loca_parcel__0ecb78_idx'), models.Index(fields=['-timestamp'], name='driver_loca_timesta_cd8ffd_idx')],
            },
        ),
    ]
