# Generated by Django 5.2.9 on 2026-01-06 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0005_remove_parcel_drop_stop_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('mini_truck', 'Mini Truck'), ('large_truck', 'Large Truck')], default='mini_truck', max_length=20)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0.0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_drivers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_assignment', to='client.parcel')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='admin_dashboard.driver')),
            ],
            options={
                'db_table': 'admin_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='admin_dashboard.driver')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_locations', to='client.parcel')),
            ],
            options={
                'db_table': 'admin_driver_locations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
