# Generated by Django 5.2.9 on 2026-01-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('mini_truck', 'Mini Truck'), ('large_truck', 'Large Truck')], default='car', max_length=20),
        ),
    ]
