# Generated by Django 5.2.9 on 2026-01-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='drop_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Drop location latitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='drop_lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Drop location longitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Pickup location latitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Pickup location longitude', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='current_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcelstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], max_length=20),
        ),
    ]
