# Generated by Django 5.2.9 on 2026-01-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_parcel_drop_lat_parcel_drop_lng_parcel_pickup_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='current_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcelstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], max_length=20),
        ),
    ]
