# Generated by Django 5.2.9 on 2026-01-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_parcel_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='current_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='requested', max_length=20),
        ),
    ]
