# Generated by Django 5.2.9 on 2026-01-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_parcel_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='drop_stop_id',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='pickup_stop_id',
        ),
    ]
